apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dewz6ose7-nodejs
  janus-idp.io/tekton: dewz6ose7-nodejs
  backstage.io/kubernetes-id: dewz6ose7-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dewz6ose7-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
